test:
  adapter: postgresql
  encoding: unicode
  database: device_app
  pool: 5
  username: dev
  password: 123456
  host: localhost 

development:
  adapter: postgresql
  encoding: unicode
  database: device_app
  pool: 5
  username: dev
  password: 123456
  host: localhost 

production:
  adapter: postgresql
  encoding: unicode
  database: device_app1
  pool: 5
  username: dev
  password: 123456
  host: localhost 